language: android
android:
  components:
    - tools
    - build-tools-27.0.2
    - android-27
before_install:
    - yes | sdkmanager "platforms;android-27"
jdk:
    - oraclejdk8
script:
    - ./gradlew clean build
branches:
  except:
    - gh-pages
notifications:
  email: false
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
